[build]
  command = "npm run build"
  publish = "_site/"

[build.environment]
  RUBY_VERSION = "3.3.5"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "staging"

[dev]
  command = "npm run start"
  publish = "_site/"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "andrewstiefel"
  imagesPath = "/assets/img"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"
